// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfmdbomweaskbomjhbuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbWRib213ZWFza2JvbWpoYnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NDA1MzAsImV4cCI6MjA4MDQxNjUzMH0._qRzkOD26S-0KT8HAFyQX-SPLyuM74dh5vZPYMtTiHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
